# **Numpy**
* NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.
* Most computational packages providing scientific functionality use NumPy's array objects as the entity for data exchange.
* Some of the unique features find in NumPy:
  * ndarray, an efficient multidimensional array providing **fast array-oriented arithmetic operations** and flexible broadcasting capabilities.
  * Mathematical functions for **fast operations on entire arrays of data without having to write loops**.
  * Tools for reading/writing array **data to disk** and **working with memory-mapped** files.
  * Linear algebra, random number generation, and Fourier transform capabilities.
  * A **C API for connecting NumPy with libraries** written in C, C++, or FORTRAN.

**For most data analysis applications, the main areas of functionality focused on are:**
  * Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations.
  * Common array algorithms like sorting, unique, and set operations
  * Efficient descriptive statistics and aggregating/summarizing data
  * Data alignment and relational data manipulations for merging and joining
together heterogeneous datasets
  * Expressing conditional logic as array expressions instead of loops with if-elifelse branches
  * Group-wise data manipulations (aggregation, transformation, function application)

**One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. There are a number of reasons for this:**
  * NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy's library of algorithms written in the C language can operate on this memory without any type checking or other overhead.
  * NumPy arrays also use much less memory than built-in Python sequences.
  * NumPy operations perform complex computations on entire arrays without the need for Python for loops.

**To measure performance difference, consider a NumPy array of one million integers, and the equivalent Python list:**


# NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 17 ms, sys: 11.7 ms, total: 28.7 ms
Wall time: 32.1 ms
CPU times: user 615 ms, sys: 253 ms, total: 868 ms
Wall time: 881 ms


## The NumPy ndarray: A Multidimensional Array Object

* Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.
* The ndarray object can be accessed by using the 0 based indexing.
* Each element of the Array object contains the same size in the memory.


* One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python.
* Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

In [ ]:
data = np.random.randn(2, 3)
data

array([[-0.17406534,  0.72676218,  0.63145288],
       [ 0.26957633,  0.09079359,  0.80024226]])

In [ ]:
data * 10

array([[-1.74065344,  7.26762181,  6.31452884],
       [ 2.69576331,  0.90793595,  8.00242258]])

* In the above example all of the elements have been multiplied by 10.

In [ ]:
data + data

array([[-0.34813069,  1.45352436,  1.26290577],
       [ 0.53915266,  0.18158719,  1.60048452]])

* In the above example the corresponding values in each “cell” in the array have been added to each other.

* An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type.
* Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array:

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

### Creating ndarrays

* The easiest way to create an array is to use the array function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data.

* The syntax is given below



  > **numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)**

* The parameters are described in the following table

<p align="center">
    <img src="http://raghudathesh.weebly.com/uploads/4/8/9/6/48968251/3_orig.png">
</p>


* For example, a list is a good candidate for conversion:

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

* Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

* Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape inferred from the data.
* We can confirm this by inspecting the ndim and shape attributes:

In [ ]:
arr2.ndim

(2, 4)

In [ ]:
arr2.shape

(2, 4)

* Unless explicitly specified (more on this later), np.array tries to infer a good data type (like int, foat etc) for the array that it creates.
* The data type is stored in a special dtype metadata object; for example, in the previous two examples we have:

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int64')

* In addition to np.array, there are a number of other functions for creating new arrays.

# Ex:
* zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape.
* Empty creates an array without initializing its values to any particular value.
* To create a higher dimensional array with these methods, pass a tuple for the shape:

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2, 3, 2))

array([[[5.06245341e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

# Note:
* It’s not safe to assume that np.empty will return an array of all zeros.
* In some cases, it may return uninitialized “garbage” values.

* **arange** is an array-valued version of the built-in Python range function:

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* Table below shows a short list of standard array creation functions.
* Since NumPy is focused on numerical computing, the data type, if not specified, will in many cases be float64 (floating point).

<p align="center">
    <img src="http://raghudathesh.weebly.com/uploads/4/8/9/6/48968251/1_orig.png">
</p>

### Data Types for ndarrays

* The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data:

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

* **dtypes** are a source of NumPy’s flexibility for interacting with data coming from other systems.
* In most cases they provide a mapping directly onto an underlying disk or memory representation, which makes it easy to read and write binary streams of data to disk and also to connect to code written in a low-level language like C or Fortran.
* The numerical dtypes are named the same way: a type name, like float or int, followed by a number indicating the number of bits per element.
* A standard doubleprecision floating-point value (what’s used under the hood in Python’s float object) takes up 8 bytes or 64 bits. Thus, this type is known in NumPy as float64.
*Table below provides a full listing of NumPy’s supported data types.

<p align="center">
    <img src="http://raghudathesh.weebly.com/uploads/4/8/9/6/48968251/2_orig.png">
</p>

* You can explicitly convert or cast an array from one dtype to another using ndarray’s **astype method**:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


* In the above example, integers were cast to floating point.
* If I cast some floating-point numbers to be of integer dtype, the decimal part will be truncated:

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


* If you have an array of strings representing numbers, you can use **astype** to convert them to numeric form:

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

# Note:
* It’s important to be cautious when using the numpy.string_ type, as string data in NumPy is fixed size and may truncate input
without warning.
If casting were to fail for some reason (like a string that cannot be converted to float64), a ValueError will be raised.

# Extra
* We can use another array’s dtype attribute:

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Extra
* There are shorthand type code strings you can also use to refer to a dtype:

In [ ]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

# Arithmetic with NumPy Arrays

* Arrays are important because **they enable you to express batch operations on data** without writing any for loops.
* **NumPy users call this vectorization**. Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

* Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [ ]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

* Comparisons between arrays of the same size yield boolean arrays:

In [ ]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

* **Operations between differently sized arrays is called broadcasting and will be discussed later**.

# Basic Indexing and Slicing

* NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements.
* One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

* As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection.
* An important first distinction from Python’s built-in lists is that array slices are views on the original array.
* This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

* Now,  **change values in arr_slice, the mutations are reflected in the original
array arr**:

In [ ]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

* The **“bare”** slice [:] will assign to all values in an array:

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

* If you are new to NumPy, you might be surprised by this, especially if you have used
other array programming languages that copy data more eagerly.
*  As NumPy has been designed to be able to work with very large arrays, you could imagine performance and memory problems if NumPy insisted on always copying data.

* With higher dimensional arrays, you have many more options.
* In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

* The individual elements in array can be accessed recursively. For this pass a comma-separated list of indices to select individual elements.

In [5]:
arr2d[0, 2]

3

In [7]:
arr2d[1][2]

6

* In multidimensional arrays, if you omit later indices, the returned object will be a
lower dimensional ndarray consisting of all the data along the higher dimensions.
* So
in the 2 × 2 × 3 array arr3d:

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

* arr3d[0] is a 2 × 3 array:

In [ ]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

* Both scalar values and arrays can be assigned to arr3d[0]:

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

*  arr3d[1, 0] gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array:

In [ ]:
arr3d[1, 0]

array([7, 8, 9])

* This expression is the same as though we had indexed in two steps:

In [ ]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x[0]

array([7, 8, 9])

* Note that in all of these cases where subsections of the array have been selected, the returned arrays are views.

# Indexing with slices

* Like one-dimensional objects such as Python lists, ndarrays can be sliced with the
familiar syntax:

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

* Consider the two-dimensional array from before, arr2d. Slicing this array is a bit
different:

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

* As you can see, it has sliced along axis 0, the first axis.
* A slice, therefore, selects a
range of elements along an axis. It can be helpful to read the expression arr2d[:2] as **select the first two rows of arr2d**.

In [ ]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

**Guess the output**

In [ ]:
arr2d[:2, 0:]

* When slicing like this, always obtain array views of the same number of dimensions.
* By mixing integer indexes and slices, you get lower dimensional slices.

* For example, We can select the second row but only the first two columns like so:

In [ ]:
arr2d[1, :2]

array([4, 5])

* Similarly, we can select the third column but only the first two rows like so:

In [ ]:
arr2d[:2, 2]

array([3, 6])

* A colon by itself means to take the entire
axis, so you can slice only higher dimensional axes by doing:

In [ ]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

* The Instruction can be read as select all the rows and first column elements.

* Assigning to a slice expression assigns to the whole selection:

In [ ]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing
* Let’s consider an example where we have some data in an array and an array of names
with duplicates.
* We going to use here the randn function in **numpy.random** to generate some random normally distributed data:

In [9]:
names = np.array(['Mohit', 'Varshini', 'Sunil', 'Mohit', 'Varshini', 'Sunil', 'Sunil'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Mohit' 'Varshini' 'Sunil' 'Mohit' 'Varshini' 'Sunil' 'Sunil']
[[ 1.61573158 -0.21467493 -0.55691091 -1.35529545]
 [ 0.63141381 -0.5910019   0.34113241  0.72124421]
 [-1.46798961  0.21982993  0.83232813 -1.06998477]
 [ 0.62967722  0.17273545  0.97245692 -1.13220514]
 [ 1.58912009  1.21402402 -1.17556876 -0.8562653 ]
 [ 0.10232066  1.62910022 -0.87208083 -1.26009825]
 [ 1.46412524 -0.60206117 -1.24660508 -1.06261898]]


* Suppose each name corresponds to a row in the data array and we wanted to select
all the rows with corresponding name 'Mohit'.
* Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized.
* Thus, comparing names with the string 'Mohit' yields a boolean array:

In [10]:
names == 'Mohit'

array([ True, False, False,  True, False, False, False])

* This boolean array can be passed when indexing the array:

In [12]:
data[names == 'Mohit']

array([[ 1.61573158, -0.21467493, -0.55691091, -1.35529545],
       [ 0.62967722,  0.17273545,  0.97245692, -1.13220514]])

* The boolean array must be of the same length as the array axis it’s indexing.
* You can even mix and match boolean arrays with slices or integers.

* Here we select from the rows where names == 'Mohit' and index the columns, too:

In [13]:
data[names == 'Mohit', 2:]

array([[-0.55691091, -1.35529545],
       [ 0.97245692, -1.13220514]])

In [14]:
data[names == 'Mohit', 3]

array([-1.35529545, -1.13220514])

* * To select everything but 'Mohit', you can either use **!=** or negate the condition using **~**:

In [15]:
names != 'Mohit'

array([False,  True,  True, False,  True,  True,  True])

In [16]:
data[~(names == 'Mohit')]

array([[ 0.63141381, -0.5910019 ,  0.34113241,  0.72124421],
       [-1.46798961,  0.21982993,  0.83232813, -1.06998477],
       [ 1.58912009,  1.21402402, -1.17556876, -0.8562653 ],
       [ 0.10232066,  1.62910022, -0.87208083, -1.26009825],
       [ 1.46412524, -0.60206117, -1.24660508, -1.06261898]])

* The ~ operator can be useful when you want to invert a general condition:

In [17]:
cond = names == 'Mohit'
data[~cond]

array([[ 0.63141381, -0.5910019 ,  0.34113241,  0.72124421],
       [-1.46798961,  0.21982993,  0.83232813, -1.06998477],
       [ 1.58912009,  1.21402402, -1.17556876, -0.8562653 ],
       [ 0.10232066,  1.62910022, -0.87208083, -1.26009825],
       [ 1.46412524, -0.60206117, -1.24660508, -1.06261898]])

* Selecting two of the three names to combine multiple boolean conditions, use
boolean arithmetic operators like & (and) and | (or):

In [18]:
mask = (names == 'Mohit') | (names == 'Sunil')
mask

array([ True, False,  True,  True, False,  True,  True])

In [19]:
data[mask]

array([[ 1.61573158, -0.21467493, -0.55691091, -1.35529545],
       [-1.46798961,  0.21982993,  0.83232813, -1.06998477],
       [ 0.62967722,  0.17273545,  0.97245692, -1.13220514],
       [ 0.10232066,  1.62910022, -0.87208083, -1.26009825],
       [ 1.46412524, -0.60206117, -1.24660508, -1.06261898]])

* Selecting data from an array by boolean indexing always creates a copy of the data,
even if the returned array is unchanged.

* Setting values with boolean arrays works in a common-sense way.
* To set all of the negative values in data to 0 we need only do:

In [20]:
data[data < 0] = 0
data

array([[1.61573158, 0.        , 0.        , 0.        ],
       [0.63141381, 0.        , 0.34113241, 0.72124421],
       [0.        , 0.21982993, 0.83232813, 0.        ],
       [0.62967722, 0.17273545, 0.97245692, 0.        ],
       [1.58912009, 1.21402402, 0.        , 0.        ],
       [0.10232066, 1.62910022, 0.        , 0.        ],
       [1.46412524, 0.        , 0.        , 0.        ]])

* Setting whole rows or columns using a one-dimensional boolean array is also easy:

In [21]:
data[names != 'Varshini'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.63141381, 0.        , 0.34113241, 0.72124421],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.58912009, 1.21402402, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

### Fancy Indexing

* Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
* Suppose we had an 8 × 4 array:

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

* To select out a subset of the rows in a particular order, you can simply pass a list or
ndarray of integers specifying the desired order:

In [ ]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

* Using negative indices selects rows from
the end:

In [ ]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

* Passing multiple index arrays does something slightly different; it selects a onedimensional array of elements corresponding to each tuple of indices:

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

* Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected. Regardless of
how many dimensions the array has (here, only 2), the result of fancy indexing is
always one-dimensional.

# Note:
* Keep in mind that fancy indexing, unlike slicing, always copies the data into a new
array.

### Transposing Arrays and Swapping Axes
* Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything.
* Arrays have the transpose method and also the
special T attribute:

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

* When doing matrix computations, you may do this very often for example, when computing the inner matrix product using np.dot:

In [ ]:
arr = np.random.randn(6, 3)
arr

array([[-0.00718572, -0.20022277, -1.26057403],
       [-0.9569538 ,  0.26044122, -1.3634736 ],
       [ 0.60256131, -1.44772897,  0.83503816],
       [-0.96793901, -0.7622255 ,  1.18116813],
       [ 0.40691467, -1.96490864,  0.0403457 ],
       [-0.96404316,  0.03334688, -0.0567573 ]])

In [ ]:
np.dot(arr.T, arr)

array([[ 3.31075703, -1.2140471 ,  0.7448361 ],
       [-1.2140471 ,  6.64680362, -2.2931028 ],
       [ 0.7448361 , -2.2931028 ,  5.54540319]])

* For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute the axes (for extra mind bending):

In [3]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

# **arr.transpose((num_sub_array, X_axis(should be same for both), Y_axis))**


Case1:

In [8]:
arr.transpose((0, 1, 2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

Case2: Changing sub_array and X_axis

  Here in frist sub array rows of first orignal sub array will be there

In [4]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [6]:
arr.transpose((0, 2, 1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

* Here, the axes have been reordered with the second axis first, the first axis second,
and the last axis unchanged.

* Simple transposing with **.T** is a special case of swapping axes. ndarray has the method
swapaxes, which takes a pair of axis numbers and switches the indicated axes to rear‐
range the data:

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

* swapaxes similarly returns a view on the data without making a copy.

## Universal Functions: Fast Element-Wise Array Functions

In [ ]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y)

In [ ]:
arr = np.random.randn(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

In [ ]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

## Array-Oriented Programming with Arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close('all')

### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

### Mathematical and Statistical Methods

In [ ]:
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(axis=0)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

### Methods for Boolean Arrays

In [ ]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = np.random.randn(6)
arr
arr.sort()
arr

In [ ]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and Other Set Logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File Input and Output with Arrays

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

## Linear Algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Pseudorandom Number Generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

In [ ]:
np.random.seed(1234)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)

## Example: Random Walks

In [ ]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [ ]:
plt.figure()

In [ ]:
plt.plot(walk[:100])

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating Many Random Walks at Once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))

## Conclusion